config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  root to: "home#index" 

  resources :bots

  resources :games, only: [:new]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bot.rb
class Bot < ApplicationRecord
  
  belongs_to :user
  has_many :games


end

app/models/game.rb
class Game < ApplicationRecord
  
  belongs_to :bot_1, class_name: :Bot
  belongs_to :bot_2, class_name: :Bot


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


    def index
        logger.debug "PRINTING"
      render "index"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<div id="arena">
  <div id="notifications"></div>
  <div id="turn-marker"><span id="team-allowed-to-move">white</span>'s turn</div>
  <div id="W-captures" class="captures">
    <br><br><br>
  </div>
  <table id="chess-board">
    <tr id="8rank" class="no-border">
      <td class="chess-tile  white-tile square-a8" id="a8">
      </td>
      <td class="chess-tile  black-tile square-b8" id="b8">
      </td>
      <td class="chess-tile  white-tile square-c8" id="c8">
      </td>
      <td class="chess-tile  black-tile square-d8" id="d8">
      </td>
      <td class="chess-tile  white-tile square-e8" id="e8">
      </td>
      <td class="chess-tile  black-tile square-f8" id="f8">
      </td>
      <td class="chess-tile  white-tile square-g8" id="g8">
      </td>
      <td class="chess-tile  black-tile square-h8" id="h8">
      </td>
    </tr>
    <tr id="7rank" class="no-border">
      <td class="chess-tile  black-tile square-a7" id="a7">
      </td>
      <td class="chess-tile  white-tile square-b7" id="b7">
      </td>
      <td class="chess-tile  black-tile square-c7" id="c7">
      </td>
      <td class="chess-tile  white-tile square-d7" id="d7">
      </td>
      <td class="chess-tile  black-tile square-e7" id="e7">
      </td>
      <td class="chess-tile  white-tile square-f7" id="f7">
      </td>
      <td class="chess-tile  black-tile square-g7" id="g7">
      </td>
      <td class="chess-tile  white-tile square-h7" id="h7">
      </td>
    </tr>

    <tr id="6rank" class="no-border">
      <td class="chess-tile  white-tile square-a6" id="a6">
      </td>
      <td class="chess-tile  black-tile square-b6" id="b6">
      </td>
      <td class="chess-tile  white-tile square-c6" id="c6">
      </td>
      <td class="chess-tile  black-tile square-d6" id="d6">
      </td>
      <td class="chess-tile  white-tile square-e6" id="e6">
      </td>
      <td class="chess-tile  black-tile square-f6" id="f6">
      </td>
      <td class="chess-tile  white-tile square-g6" id="g6">
      </td>
      <td class="chess-tile  black-tile square-h6" id="h6">
      </td>
    </tr>
      
    <tr id="5rank" class="no-border">
      <td class="chess-tile  black-tile square-a5" id="a5">
      </td>
      <td class="chess-tile  white-tile square-b5" id="b5">
      </td>
      <td class="chess-tile  black-tile square-c5" id="c5">
      </td>
      <td class="chess-tile  white-tile square-d5" id="d5">
      </td>
      <td class="chess-tile  black-tile square-e5" id="e5">
      </td>
      <td class="chess-tile  white-tile square-f5" id="f5">
      </td>
      <td class="chess-tile  black-tile square-g5" id="g5">
      </td>
      <td class="chess-tile  white-tile square-h5" id="h5">
      </td>
    </tr>

    <tr id="4rank" class="no-border">
      <td class="chess-tile  white-tile square-a4" id="a4">
      </td>
      <td class="chess-tile  black-tile square-b4" id="b4">
      </td>
      <td class="chess-tile  white-tile square-c4" id="c4">
      </td>
      <td class="chess-tile  black-tile square-d4" id="d4">
      </td>
      <td class="chess-tile  white-tile square-e4" id="e4">
      </td>
      <td class="chess-tile  black-tile square-f4" id="f4">
      </td>
      <td class="chess-tile  white-tile square-g4" id="g4">
      </td>
      <td class="chess-tile  black-tile square-h4" id="h4">
      </td>
    </tr>

    <tr id="3rank" class="no-border">
      <td class="chess-tile  black-tile square-a3" id="a3">
      </td>
      <td class="chess-tile  white-tile square-b3" id="b3">
      </td>
      <td class="chess-tile  black-tile square-c3" id="c3">
      </td>
      <td class="chess-tile  white-tile square-d3" id="d3">
      </td>
      <td class="chess-tile  black-tile square-e3" id="e3">
      </td>
      <td class="chess-tile  white-tile square-f3" id="f3">
      </td>
      <td class="chess-tile  black-tile square-g3" id="g3">
      </td>
      <td class="chess-tile  white-tile square-h3" id="h3">
      </td>
    </tr>

    <tr id="2rank" class="no-border">
      <td class="chess-tile  white-tile square-a2" id="a2">
      </td>
      <td class="chess-tile  black-tile square-b2" id="b2">
      </td>
      <td class="chess-tile  white-tile square-c2" id="c2">
      </td>
      <td class="chess-tile  black-tile square-d2" id="d2">
      </td>
      <td class="chess-tile  white-tile square-e2" id="e2">
      </td>
      <td class="chess-tile  black-tile square-f2" id="f2">
      </td>
      <td class="chess-tile  white-tile square-g2" id="g2">
      </td>
      <td class="chess-tile  black-tile square-h2" id="h2">
      </td>
    </tr>

    <tr id="1rank" class="no-border">
      <td class="chess-tile  black-tile square-a1" id="a1">
      </td>
      <td class="chess-tile  white-tile square-b1" id="b1">
      </td>
      <td class="chess-tile  black-tile square-c1" id="c1">
      </td>
      <td class="chess-tile  white-tile square-d1" id="d1">
      </td>
      <td class="chess-tile  black-tile square-e1" id="e1">
      </td>
      <td class="chess-tile  white-tile square-f1" id="f1">
      </td>
      <td class="chess-tile  black-tile square-g1" id="g1">
      </td>
      <td class="chess-tile  white-tile square-h1" id="h1">
      </td>
    </tr>
  </table>
  <div id="B-captures" class="captures">
    <br><br><br>
  </div>
</div>

<button id="undo-button">
  undo
</button>
<button id="pause-button">pause</button>

app/views/home/index.html.erb
  <%= button_to "Play chess against a very dumb bot!", new_game_path, method: :get %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetitledPrincessCarolynProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>